//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeekerTable
    {
        public int JobSeekerID { get; set; }
        public int PostJobID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNo { get; set; }
        public string Skills { get; set; }
        public string ExperienceID { get; set; }
        public int UserID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Education { get; set; }
    
        public virtual PostJobTable PostJobTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
